### ISSUE TITLE
random error YXDB file, where YXDB created using 2023.1

### ISSUE THREAD

**Issue by DDXBIZ** [tlarsendataguy-yxdb/yxdb-go#1]
Hi,

Attach is the file we created, and we are using go, trying to read the metadata field list, using the example code you had.

[policyList.zip](https://github.com/tlarsendataguy-yxdb/yxdb-go/files/13910653/policyList.zip)

we are struggling to read this file and not sure how we can debug and identified what is wrong. 

and would you have an example in GO on reading this file (field list) and the records within.

Your advice is greatly appreciated.

Thanks
David

**Comment by tlarsendataguy** [comment]
Hi David,

You have encountered a known limitation. When Alteryx released the Amp engine, they updated the format of YXDB files generated by said engine. Unfortunately, Alteryx has not released the technical specs of Amp-compatible YXDB files. This means I am unable to make this package compatible with the newer YXDB format.

You can still generate original-format YXDB files using the newer versions of Alteryx by clicking the checkbox titled 'AMP Only: Compatible with 18.1 and Earlier' in the output tool
![Screenshot 2024-01-11 at 10 42 16 PM](https://github.com/tlarsendataguy-yxdb/yxdb-go/assets/13069719/1a8b3de1-b1c9-4ca7-bd2c-9ae6b68a2a1e)

I am hoping someday Alteryx will release the specs of the new format so I can make this package compatible with all YXDB formats.

Tom

**Comment by DDXBIZ** [comment]
Hi Tom,

Thank You so much for your advice on this.

By the way, do you have any sample code for GO reading the data within an alteryx YXDB?

I'm struggling to get it to work... as I only managed to get the fieldlist to work for now.

any advice is greatly appreciated.

David

**Comment by tlarsendataguy** [comment]
Hi David,

I would recommend starting with the unit tests in this package. The tests in [reader_test.go](https://github.com/tlarsendataguy-yxdb/yxdb-go/blob/master/reader_test.go) are end-to-end tests of the reader and should serve well as examples.

In particular, the `TestLotsOfRecords` and `TestTutorialData` tests are good starting points.

`TestLotsOfRecords` reads and calculates a sum from a numeric field in the test file.

`TestTutorialData` counts the number of times the string 'Mr.' shows up in a column in another test file.

Both are trivial examples that should help you get started. If you have ever used the sql package in Go, this package operates similarly to iterate through records.

If you still have questions after reviewing the tests, feel free to ask them here. Or, if you would rather the questions not be asked in a public setting, we can move to e-mail or some other channel.

**Comment by DDXBIZ** [comment]
Hi Tom,

Many Thanks for the advice.. I managed to work out how to read the record, by column type, and then making it into a single record.

Thanks
David
